net_status = {
    'SYN_SENT': '请求',
    'LISTEN': '监听',
    'ESTABLISHED': '已建立',
    'NONE': '未知',
    'CLOSE_WAIT': '中断',
    'LAST_ACK': '等待关闭'
}

wink = ['SYSTEM', 'SYSTEMIDLEPROCESS', 'SMSS.EXE',
        'CSRSS.EXE', 'WININIT.EXE', 'WINLOGON.EXE', 'SERVICES.EXE',
        'LSASS.EXE', 'SVCHOST.EXE', 'DWM.EXE', 'MEMORYCOMPRESSION',
        'TASKHOSTW.EXE', 'RUNTIMEBROKER.EXE', 'EXPLORER.EXE', 'SHELLEXPERIENCEHOST.EXE',
        'APPLICATIONFRAMEHOST.EXE', 'SYSTEMSETTINGS.EXE', 'WMIPRVSE.EXE', 'PLUGIN_HOST.EXE',
        'SPOOLSV.EXE', 'DASHOST.EXE', 'SIHOST.EXE', 'CONHOST.EXE', 'DLLHOST.EXE', 'TASKLIST.EXE',
        'NVCONTAINER.EXE', 'SEARCHUI.EXE', 'REGISTRY', 'FONTDRVHOST.EXE', 'IGFXCUISERVICE.EXE',
        'NVTELEMETRYCONTAINER.EXE', 'SECURITYHEALTHSERVICE.EXE', 'PRESENTATIONFONTCACHE.EXE',
        'SEARCHINDEXER.EXE', 'IGFXEM.EXE', 'IGFXHK.EXE', 'CTFMON.EXE', 'SMARTSCREEN.EXE', 'CTFMON.EXE',
        'SETTINGSYNCHOST.EXE', 'WINDOWSINTERNAL.COMPOSABLESHELL.EXPERIENCES.TEXTINPUT.INPUTAPP.EXE',
        'CHSIME.EXE', 'AUDIODG.EXE', 'USYSDIAG.EXE', 'SEARCHPROTOCOLHOST.EXE', 'SEARCHFILTERHOST.EXE']

linux_ps = [
    'LOGIN', 'KBLOCKD', 'EDAC-POLLER', 'KHUGEPAGED', 'SCSI_TMF_0', 'WATCHDOG/0', 'XFS-CONV/SDB', 'IRQ/16-VMWGFX',
    'NETNS', 'BIOSET', 'DHCLIENT',
    'KINTEGRITYD', 'KPSMOUSED', 'XFS-BUF/SDA1', 'SCSI_EH_2', 'MD', 'KSMD', 'KDEVTMPFS', 'SCSI_TMF_2', 'TTM_SWAP',
    'KHUNGTASKD', 'SYSTEMD-UDEVD', 'TUNED',
    'XFS-LOG/SDA1', 'XFS-CIL/SDA1', 'KWORKER/0:0', 'CROND', 'MPT_POLL_0', 'XFS-LOG/SDA3', 'KMPATH_RDACD',
    'KWORKER/U256:1', 'RCU_SCHED', 'LRU-ADD-DRAIN',
    'SFTP-SERVER', 'WATCHDOGD', 'XFS-DATA/SDB', 'XFS-RECLAIM/SDB', 'SCSI_EH_1', 'XFSAILD/SDA3', 'LVMETAD', 'MASTER',
    'XFSALLOC', 'XFS-DATA/SDA3', 'XFS-CONV/SDA3',
    'RSYSLOGD', 'QMGR', 'XFS-LOG/SDB', 'ATA_SFF', 'SYSTEMD-LOGIND', 'SCSI_EH_0', 'KWORKER/U256:2', 'NETWORKMANAGER',
    'KWORKER/0:1', 'KWORKER/0:0H',
    'KWORKER/0:1H', 'KWORKER/0:3', 'DEFERWQ', 'SYSTEMD-JOURNALD', 'XFSAILD/SDB', 'RCU_BH', 'POLKITD', 'VMTOOLSD',
    'XFS-EOFBLOCKS/S', 'NFIT', 'XFS-BUF/SDA3',
    'KWORKER/0:2', 'XFS-BUF/SDB', 'SYSTEMD', 'IPV6_ADDRCONF', 'SSHD', 'MPT/0', 'XFS-CIL/SDA3', 'KSWAPD0',
    'XFSAILD/SDA1', 'MIGRATION/0', 'WRITEBACK',
    'AUDITD', 'KTHROTLD', 'KTHREADD', 'KAUDITD', 'KSOFTIRQD/0', 'XFS-CONV/SDA1', 'CRYPTO', 'XFS_MRU_CACHE', 'KALUAD',
    'XFS-RECLAIM/SDA', 'XFS-DATA/SDA1', 'VSFTPD',
    'DBUS-DAEMON', 'XFS-CIL/SDB', 'SCSI_TMF_1', 'VGAUTHSERVICE', 'BASH'
]
